var BilData = [
  {
    "Bilde I.D.": "",
    "Merke": "Audi",
    "Modell": "e-tron",
    "Type": "55",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "415",
    "Pris": "652061",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Audi",
    "Modell": "e-tron",
    "Type": "55 advanced plus",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "415",
    "Pris": "739580",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Audi",
    "Modell": "e-tron",
    "Type": "Exclusive",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "415",
    "Pris": "821900",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "BMW",
    "Modell": "i3",
    "Type": "120Ah",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "310",
    "Pris": "309000",
    "Størrelse": "Liten",
    "Terning": "4",
    "Sitteplasser": "4"
  },
  {
    "Bilde I.D.": "",
    "Merke": "BMW",
    "Modell": "i3",
    "Type": "120Ah Charged",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "310",
    "Pris": "318900",
    "Størrelse": "Liten",
    "Terning": "4",
    "Sitteplasser": "4"
  },
  {
    "Bilde I.D.": "",
    "Merke": "BMW",
    "Modell": "i3",
    "Type": "120Ah Charged +",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "310",
    "Pris": "338900",
    "Størrelse": "Liten",
    "Terning": "4",
    "Sitteplasser": "4"
  },
  {
    "Bilde I.D.": "",
    "Merke": "BMW",
    "Modell": "i3",
    "Type": "120Ah fully Charged",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "310",
    "Pris": "368900",
    "Størrelse": "Liten",
    "Terning": "4",
    "Sitteplasser": "4"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "Citroen",
    "Modell": "Berlingo",
    "Type": "Electricue Proff L1",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "170",
    "Pris": "227500",
    "Størrelse": "Mellom",
    "Terning": "-",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Citron",
    "Modell": "Berlingo",
    "Type": "Electricue Proff L2",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "170",
    "Pris": "235500",
    "Størrelse": "Mellom",
    "Terning": "-",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Citroen",
    "Modell": "C-Zero",
    "Type": "Feel",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "150",
    "Pris": "144380",
    "Størrelse": "Liten",
    "Terning": "5",
    "Sitteplasser": "4"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "Jaguar",
    "Modell": "i-Pace",
    "Type": "400hk AWD Auto S",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "480",
    "Pris": "639 950",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Jaguar",
    "Modell": "i-Pace",
    "Type": "400hk AWD Auto SE",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "480",
    "Pris": "714 950",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Jaguar",
    "Modell": "i-Pace",
    "Type": "400hk AWD Auto HSE",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "480",
    "Pris": "764950",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "Hyundai",
    "Modell": "Ioniq",
    "Type": "EV",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "280",
    "Pris": "244000",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Hyundai",
    "Modell": "Ioniq",
    "Type": "Teknikk",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "280",
    "Pris": "269000",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Hyundai",
    "Modell": "Kona Electric",
    "Type": "Teknikk",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "449",
    "Pris": "325000",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "DS",
    "Modell": "E-Tense",
    "Type": "136 So Chic",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "300",
    "Pris": "319 900",
    "Størrelse": "Liten",
    "Terning": "-",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "DS",
    "Modell": "E-Tense",
    "Type": "136 Grand Chic",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "300",
    "Pris": "349900",
    "Størrelse": "Liten",
    "Terning": "-",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "Kia",
    "Modell": "E-Niro",
    "Type": "First Edition",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "485",
    "Pris": "370600",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Kia",
    "Modell": "E-Soul",
    "Type": "Classic",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "250",
    "Pris": "228100",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Kia",
    "Modell": "E-Soul",
    "Type": "Active",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "250",
    "Pris": "228100",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Kia",
    "Modell": "E-Soul",
    "Type": "Exclusive",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "250",
    "Pris": "265100",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "Mercedes-Benz",
    "Modell": "EQC",
    "Type": "400 4MATIC",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "450",
    "Pris": "-",
    "Størrelse": "Stor",
    "Terning": "-",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "Mitsubishi",
    "Modell": "i-Miev",
    "Type": "16 kWh",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "105",
    "Pris": "149900",
    "Størrelse": "Liten",
    "Terning": "5",
    "Sitteplasser": "4"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "Nissan",
    "Modell": "Leaf",
    "Type": "40kWh Acenta",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "270",
    "Pris": "278000",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Nissan",
    "Modell": "Leaf",
    "Type": "40kWh N-Conneca",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "270",
    "Pris": "294500",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Nissan",
    "Modell": "Leaf",
    "Type": "40kWh Tekna",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "270",
    "Pris": "307500",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Nissan",
    "Modell": "Leaf",
    "Type": "62kWh e+ N-Conneca",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "385",
    "Pris": "346800",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Nissan",
    "Modell": "Leaf",
    "Type": "62 kWh e+ Tekna",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "385",
    "Pris": "375000",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Nissan",
    "Modell": "E-NV200",
    "Type": "Evalia 40 kWt 5-s",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "200",
    "Pris": "322840",
    "Størrelse": "Stor",
    "Terning": "4",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Nissan",
    "Modell": "E-NV200",
    "Type": "Evalia 40 kWt 7-s",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "200",
    "Pris": "334840",
    "Størrelse": "Stor",
    "Terning": "4",
    "Sitteplasser": "7"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Nissan",
    "Modell": "E-NV200",
    "Type": "Comfort Plus 40 kWt",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "200",
    "Pris": "288990",
    "Størrelse": "Stor",
    "Terning": "4",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Nissan",
    "Modell": "E-NV200",
    "Type": "Premium 40 kWt",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "200",
    "Pris": "305990",
    "Størrelse": "Stor",
    "Terning": "4",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Opel",
    "Modell": "Ampera-E",
    "Type": "Premium",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "423",
    "Pris": "359900",
    "Størrelse": "Mellom",
    "Terning": "6",
    "Sitteplasser": "4"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": "3"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Peugeot",
    "Modell": "iOn",
    "Type": "Active",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "150",
    "Pris": "163600",
    "Størrelse": "Liten",
    "Terning": "",
    "Sitteplasser": "3"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Peugeot",
    "Modell": "Partner Electric",
    "Type": "L1 Edition",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "170",
    "Pris": "192000",
    "Størrelse": "Mellom",
    "Terning": "-",
    "Sitteplasser": "3"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Peugeot",
    "Modell": "Partner Electric",
    "Type": "L2 Editon",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "170",
    "Pris": "200000",
    "Størrelse": "Mellom",
    "Terning": "-",
    "Sitteplasser": "3"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Peugeot",
    "Modell": "Partner Electric",
    "Type": "Mester L1",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "170",
    "Pris": "233000",
    "Størrelse": "Mellom",
    "Terning": "-",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Peugeot",
    "Modell": "Partner Electric",
    "Type": "Mester L2",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "170",
    "Pris": "241500",
    "Størrelse": "Mellom",
    "Terning": "-",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Peugeot",
    "Modell": "Partner Tepee",
    "Type": "Electricue",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "170",
    "Pris": "241500",
    "Størrelse": "Mellom",
    "Terning": "-",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Renault",
    "Modell": "Kangoo Electric",
    "Type": "Z.E.",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "270",
    "Pris": "268400",
    "Størrelse": "Mellom",
    "Terning": "3",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Renault",
    "Modell": "Kangoo Electric",
    "Type": "Maxi",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "270",
    "Pris": "260900",
    "Størrelse": "Mellom",
    "Terning": "3",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Renault",
    "Modell": "Kangoo Electric",
    "Type": "5-seter",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "270",
    "Pris": "268400",
    "Størrelse": "Mellom",
    "Terning": "3",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Renault",
    "Modell": "Twizy",
    "Type": "Intens",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "90",
    "Pris": "93000",
    "Størrelse": "Liten",
    "Terning": "4",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Renault",
    "Modell": "Zoe",
    "Type": "Z.E 40 R90 Life",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "400",
    "Pris": "245000",
    "Størrelse": "Mellom",
    "Terning": "4",
    "Sitteplasser": "4"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Renault",
    "Modell": "Zoe",
    "Type": "Z.E 40 R110 Intens",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "400",
    "Pris": "270000",
    "Størrelse": "Mellom",
    "Terning": "4",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "Smart",
    "Modell": "ForTwo",
    "Type": "Pure",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "160",
    "Pris": "169 900",
    "Størrelse": "Liten",
    "Terning": "3",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Smart",
    "Modell": "ForTwo",
    "Type": "EQ ForTwo",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "160",
    "Pris": "175 100",
    "Størrelse": "Liten",
    "Terning": "3",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Smart",
    "Modell": "ForTwo",
    "Type": "STAR",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "160",
    "Pris": "189 900",
    "Størrelse": "Liten",
    "Terning": "3",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Smart",
    "Modell": "ForTwo",
    "Type": "Cabrio",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "160",
    "Pris": "195 100",
    "Størrelse": "Liten",
    "Terning": "3",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Smart",
    "Modell": "ForTwo",
    "Type": "Cabrio STAR",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "160",
    "Pris": "199 900",
    "Størrelse": "Liten",
    "Terning": "3",
    "Sitteplasser": "2"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "Tesla",
    "Modell": "Model 3",
    "Type": "Standard Range RWD",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "415",
    "Pris": "377 020",
    "Størrelse": "Stor",
    "Terning": "-",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Tesla",
    "Modell": "Model 3",
    "Type": "Long Range AWD",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "560",
    "Pris": "459 920",
    "Størrelse": "Stor",
    "Terning": "-",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Tesla",
    "Modell": "Model 3",
    "Type": "Performance AWD",
    "Leveringstid": "",
    "": "WLTP",
    "Rekkevidde Km": "530",
    "Pris": "542 920",
    "Størrelse": "Stor",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Tesla",
    "Modell": "Model S",
    "Type": "Long Range",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "632",
    "Pris": "799 820",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Tesla",
    "Modell": "Model S",
    "Type": "Performance",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "613",
    "Pris": "882 820",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Tesla",
    "Modell": "Model X",
    "Type": "Long Range 5-s",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "565",
    "Pris": "841 320",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Tesla",
    "Modell": "Model X",
    "Type": "Long Range 7-s",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "565",
    "Pris": "866 420",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "7"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Tesla",
    "Modell": "Model X",
    "Type": "Long Range 6-s",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "565",
    "Pris": "891 320",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "6"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Tesla",
    "Modell": "Model X",
    "Type": "Performance 5-s",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "542",
    "Pris": "923 720",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Tesla",
    "Modell": "Model X",
    "Type": "Performance 7-s",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "542",
    "Pris": "948 820",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "7"
  },
  {
    "Bilde I.D.": "",
    "Merke": "Tesla",
    "Modell": "Model X",
    "Type": "Performance 6-s",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "542",
    "Pris": "973 720",
    "Størrelse": "Stor",
    "Terning": "6",
    "Sitteplasser": "6"
  },
  {
    "Bilde I.D.": "",
    "Merke": "",
    "Modell": "",
    "Type": "",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "",
    "Pris": "",
    "Størrelse": "",
    "Terning": "",
    "Sitteplasser": ""
  },
  {
    "Bilde I.D.": "",
    "Merke": "VW",
    "Modell": "eGolf",
    "Type": "35.8 kWt",
    "Leveringstid": "",
    "": "",
    "Rekkevidde Km": "229",
    "Pris": "326200",
    "Størrelse": "Mellom",
    "Terning": "5",
    "Sitteplasser": "5"
  },
  {
    "Bilde I.D.": "",
    "Merke": "VW",
    "Modell": "eUP!",
    "Type": "60 kWt",
    "Leveringstid": "",
    "": "NEDC",
    "Rekkevidde Km": "133",
    "Pris": "211300",
    "Størrelse": "Liten",
    "Terning": "-",
    "Sitteplasser": "4"
  }
]

module.exports = BilData;
